### PR TITLE
Add endpoint to get user's alert words.

### PR DESCRIPTION
**Pull request by Anupam-dagar**
Issue: #63
@aero31aero  The test was passing but while trying on a server I was getting the following error. I wasn't able to resolve it, can you take a look at it.
screenshot from 2018-08-23 11-03-47

### CODE REVIEW

**Comment by aero31aero** [comment]
Perhaps because you're trying to fetch something but have no alert words to fetch? Just a hunch, but I'll investigate soon.

**Comment by Anupam-dagar** [comment]
Yup, my current user don't have any alert words. I think instead of this error, we should show the generic "no alert words for user found" error if possible as it will make the error clear to understand.

**Comment by aero31aero** [comment]
@Anupam-dagar there was a small typo in this code: `apikey => apiKey`. Fixing that fixed this for me, and the code works as expected. We should probably work on testing/reworking our examples sometime.

**Comment by Anupam-dagar** [comment]
@aero31aero I will keep a better look on typo's from next PR onwards.

**Comment by aero31aero** [comment]
Merged manually after some changes, thanks @Anupam-dagar.

**Pull request closed without merging**
