### PR TITLE
Migrate all existing tests to be stand alone

### LINKED ISSUE #13: Units Tests failing in Local Environment as well as Travis
Debug these tests one by one to improve the codebase systematically. Refer this issue when fixing tests.

End goal: change the test command to `mocha --recursive` and have all the tests pass.

- [x] accounts.js
- [x] emojis.js
- [x] events.js
- [x] messages.js
- [x] queues.js
- [x] streams.js
- [x] typing.js
- [x] users.js
- [ ] index.js

### PR DESCRIPTION
**Pull request by aero31aero**
This is a continuation of #18 and tries to address #13.

Would add more commits to migrate more files.

### CODE REVIEW

**Comment by aero31aero** [comment]
@showell this feels ready for review. Please see if I've missed anything here. I added a bunch of TODO statements where the tests could be made more descriptive, and would tackle them/create issues for them later.

**Comment by showell** [comment]
LGTM.

**Comment by aero31aero** [comment]
Pinging @timabbott for merge when free.

**Comment by timabbott** [comment]
Merged, thanks @aero31aero!  I also gave you write access to this repo, since you've now done most of the recent work on the project.  It's still worth getting your work reviewed, but next time you can just merge once you get a positive review (and you can now merge other folks' PRs).

**Pull request merged**
