### PR TITLE
Support initialization with zuliprc

### LINKED ISSUE #8: Add support for reading configuration from a zuliprc file
Given our plans with https://github.com/zulip/zulip/issues/2327, it probably make sense to have the javascript client support reading zuliprc files.

### PR DESCRIPTION
**Pull request by arpith**
zuliprc's look like 
> [api]
> email=cordelia@zulip.com
> key=wlueAg7cQXqKpUgIaPP3dmF4vibZXal7
> site=http://localhost:9991

This PR adds support for initializing with a zuliprc. This is to fix #8

### CODE REVIEW

**Comment by timabbott** [comment]
Hmm, you might want to use a package for parsing `.ini` format files (like our `zuliprc`) like https://www.npmjs.com/package/ini ; that might handle things like comments or multiple sections automatically (I hope).

**Comment by arpith** [comment]
Thanks @timabbott :) Now using the ini package

**Comment by timabbott** [comment]
Cool!  We should support passing the filename as an argument, similar to how the Python bindings do it...

**Comment by arpith** [comment]
Done :) it can be initialized with `zulip({ zuliprc: 'a_file_name' } )`

**Pull request merged**
